# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-26 17:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='area',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='located', to='first_app.User'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='loco',
            field=models.ManyToManyField(related_name='there', to='first_app.User'),
        ),
    ]
