# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-26 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0005_auto_20180726_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='area',
            field=models.CharField(default=1, max_length=225),
            preserve_default=False,
        ),
    ]
